### PR TITLE
Add stripe branding to cc and bank forms

### PR DESCRIPTION
**Pull request by jdungan**

### CODE REVIEW

**Comment by groovecoder** [comment]
Works, but this new cc form arrangement seems confusing. :( Why is the expiration year aligned with the CVC code?

Let's do 4 rows:

Number
CVC
Expiration
Submit

**Comment by groovecoder** [comment]
We should also add stripe branding to the bank account form. Something for a contributor to do?

**Comment by jdungan** [comment]
We need to do a redesign session (post xmas).  The stripe logo was added to the bank_account_page template.

**Comment by groovecoder** [comment]
When I saved bank info (with the placeholder values), I got kicked into the "Give us extra information flow" ... and hit some issues ...

bank-info-page-typo

(Mis-aligned radio buttons & labels)
bank-info-page-misaligned

**Comment by jdungan** [comment]
OBE by #453

**Pull request closed without merging**
