### PR TITLE
upgrade jquery to 3.2.1

### LINKED ISSUE #477: Upgrade jquery
The widget has upgraded to jquery 3.2.0.  The server still uses jquery 2.0.3 and throws warnings on Firefox.  steps:

1) find jquery.-3.2.0.min.js
2) add it to the static files
3) test

### PR DESCRIPTION
**Pull request by mrmakeit**
This fixes #477.

### CODE REVIEW

**Comment by jdungan** [comment]
Close but not yet.  The jquery to updated is the file for the addon.  This changes the cdn version used by the website.

**Comment by groovecoder** [comment]
Though technically, upgrading widget jquery should be an issue in the widgets repo, right?

**Comment by jdungan** [comment]
The jquery file is delivered from the website to the iframe. (not part of the widget)

**Comment by jdungan** [comment]
p.s.  the widget upgraded to 3.2.0 awhile back.

**Comment by mrmakeit** [comment]
@jdungan I've added the static jquery entry, and updated the base template for the addon with the new jquery file.  I've tested everything i can to verify it works, but I can't submit the creditcard info while on 127.0.0.1 due to stripe csp.  everything else seems to work.

**Comment by groovecoder** [comment]
posting a bid doesn't seem to work?

`TypeError: $.ajax(...).error is not a function` at `  widget-app.js:73:24`

**Comment by groovecoder** [comment]
Now I get an SSL error on the JS call to Stripe?
```
Environment:


Request Method: GET
Request URL: https://127.0.0.1:8443/

Django Version: 1.9.13
Python Version: 2.7.11
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'corsheaders',
 'mailer',
 'rest_framework',
 'rest_framework_swagger',
 'codesy.base',
 'api',
 'auctions',
 'payments')
Installed Middleware:
('django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'csp.middleware.CSPMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'payments.middleware.IdentityVerificationMiddleware')



Traceback:

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  123.                 response = middleware_method(request)

File "/Users/lcrouch/code/codesy/codesy/payments/middleware.py" in process_request
  13.                 if not user_account.identity_verified():

File "/Users/lcrouch/code/codesy/codesy/payments/models.py" in identity_verified
  37.             stripe_account = stripe.Account.retrieve(self.account_id)

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/stripe/resource.py" in retrieve
  443.         instance.refresh()

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/stripe/resource.py" in refresh
  286.         self.refresh_from(self.request('get', self.instance_url()))

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/stripe/resource.py" in request
  208.         response, api_key = requestor.request(method, url, params, headers)

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/stripe/api_requestor.py" in request
  137.             method.lower(), url, params, headers)

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/stripe/api_requestor.py" in request_raw
  250.             method, abs_url, headers, post_data)

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/stripe/http_client.py" in request
  121.             self._handle_request_error(e)

File "/Users/lcrouch/python/codesy/lib/python2.7/site-packages/stripe/http_client.py" in _handle_request_error
  141.         raise error.APIConnectionError(msg)

Exception Type: APIConnectionError at /
Exception Value: Unexpected error communicating with Stripe.  If this problem persists,
let us know at support@stripe.com.

(Network error: SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590))
```

**Comment by mrmakeit** [comment]
Yes, the 127.0.0.1 ssl cert cant be validated, so stripe will error out.

**Comment by jdungan** [comment]
I'm seeing these errors when loading the widget and on the website:

screen shot 2017-07-23 at 2 34 39 pm
screen shot 2017-07-23 at 2 34 54 pm

**Comment by aprilchomp** [comment]
Error Occurs on Claims and Votes page. 
screen shot 2017-07-23 at 3 08 34 pm

**Comment by jdungan** [comment]
@mrmakeit Can you change to a branch name other than 'master'  Something like 'change-jquery-477' ?

**Comment by mrmakeit** [comment]
Closing to change branch name.

**Pull request closed without merging**
