### PR TITLE
Update django to 1.11.4

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
All tests are fixed. I'm spot-checking on my machine now. Could use another spot-check and then we'll want to do a QA pass on stage.

**Comment by groovecoder** [comment]
Not sure if this is related to the update, but when I clicked "Pay Me!" on an approved claim, it didn't seem to work ... there's no error on the page; it even says "Your payout was sent." ... 

image

... but in the console, it shows:

```
No such charge:
charge error: No such customer: cus_BL2L0S6EOD0jN9
No such charge:
charge error: No such customer: cus_BL2L0S6EOD0jN9
```

**Comment by groovecoder** [comment]
Weird ... even after I cleared my Stripe values in the database, I still got a bunch of the same errors. Does Stripe library cache the values or something?

**Comment by jdungan** [comment]
"cus_*" token are for credit cards.  You'll have to re-register a test credit card.  In hindsight, wiping the test data without telling anyone was quite rude.  sorry.

**Pull request merged**
