### PR TITLE
fix #307: show claims & actions on bid-list

### LINKED ISSUE #307: Bid list should show claims
Situation:  User goes to bid list on web site.   This shows offers, but does not show any pending claims.

### PR DESCRIPTION
**Pull request by groovecoder**
This adds the user's next bid and/or claim call-to-action to the bid list as well as the widget. This code needs to get out of my head and terminal and in front of someone else ...

### CODE REVIEW

**Comment by jdungan** [comment]
I think this needs us to sit in a video room and hack it out.

**Comment by groovecoder** [comment]
Monday @ 36°N?

**Comment by jdungan** [comment]
Works for me.  Breakfast again?

**Comment by groovecoder** [comment]
Yup.

**Comment by jdungan** [comment]
Multiple offers show total offers, not individual amounts.

#

**Comment by jdungan** [comment]
Changes to bid should not be allowed while a claim is submitted, waiting for votes, or approved.

**Comment by jdungan** [comment]
Please remove django-debug-toolbar

**Pull request merged**
